src/Entity/Games.php
<?php

namespace App\Entity;

use App\Repository\GamesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GamesRepository::class)
 */
class Games
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name_img;

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="game", orphanRemoval=true)
     */
    private $events;

    public function __construct()
    {
        $this->events = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNameImg(): ?string
    {
        return $this->name_img;
    }

    public function setNameImg(string $name_img): self
    {
        $this->name_img = $name_img;

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setGame($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->removeElement($event)) {
            // set the owning side to null (unless already changed)
            if ($event->getGame() === $this) {
                $event->setGame(null);
            }
        }

        return $this;
    }

}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @UniqueEntity("email")
 * @UniqueEntity("Pseudo")
 */
class Users implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = ["ROLE_PLAYER"];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Pseudo;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="users")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=UsersEvent::class, mappedBy="user", orphanRemoval=true)
     */
    private $usersEvents;

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="user")
     */
    private $events;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity=Contact::class, mappedBy="user", orphanRemoval=true)
     */
    private $contacts;

    /**
     * @ORM\OneToMany(targetEntity=Convertation::class, mappedBy="user", orphanRemoval=true)
     */
    private $convertations;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->usersEvents = new ArrayCollection();
        $this->events = new ArrayCollection();
        $this->contacts = new ArrayCollection();
        $this->convertations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUsers($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUsers() === $this) {
                $comment->setUsers(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|UsersEvent[]
     */
    public function getUsersEvents(): Collection
    {
        return $this->usersEvents;
    }

    public function addUsersEvent(UsersEvent $usersEvent): self
    {
        if (!$this->usersEvents->contains($usersEvent)) {
            $this->usersEvents[] = $usersEvent;
            $usersEvent->setUser($this);
        }

        return $this;
    }

    public function removeUsersEvent(UsersEvent $usersEvent): self
    {
        if ($this->usersEvents->removeElement($usersEvent)) {
            // set the owning side to null (unless already changed)
            if ($usersEvent->getUser() === $this) {
                $usersEvent->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setUser($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->removeElement($event)) {
            // set the owning side to null (unless already changed)
            if ($event->getUser() === $this) {
                $event->setUser(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Contact[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setUser($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getUser() === $this) {
                $contact->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Convertation[]
     */
    public function getConvertations(): Collection
    {
        return $this->convertations;
    }

    public function addConvertation(Convertation $convertation): self
    {
        if (!$this->convertations->contains($convertation)) {
            $this->convertations[] = $convertation;
            $convertation->setUser($this);
        }

        return $this;
    }

    public function removeConvertation(Convertation $convertation): self
    {
        if ($this->convertations->removeElement($convertation)) {
            // set the owning side to null (unless already changed)
            if ($convertation->getUser() === $this) {
                $convertation->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/AdministrationController.php
<?php

namespace App\Controller;

use App\Entity\Games;
use App\Entity\Users;
use App\Form\AddGamesFormType;
use App\Repository\ContactRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdministrationController extends AbstractController
{
    /**
     * @Route("/administration", name="administration")
     */
    public function index(Request $request, ContactRepository $contactRepository): Response
    {
        //Form to add new Games
        $games = new Games();
        $form = $this->createForm(AddGamesFormType::class, $games);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $games = $form->getData();
            
            //Save picture
            $file = $form['name_img']->getData();
            $file->move('images/games', $file->getClientOriginalName());
            $games->setNameImg($file->getClientOriginalName());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($games);
            $entityManager->flush();

            return $this->redirectToRoute('administration');
        }

        //Show all Games
        $showGames = $this->getDoctrine()->getRepository(Games::class)->findAll();

        //Show all Users
        $showUsers = $this->getDoctrine()->getRepository(Users::class)->findAll();

        //Show friend of user
        $friendListOne = $contactRepository->findAllFriendOfUser($this->getUser()->getId());
        $friendListTwo = $contactRepository->findAllUserOfFriend($this->getUser()->getId());

        return $this->render('administration/index.html.twig', [
            'addGamesForm' => $form->createView(),
            'showGames' => $showGames,
            'showUsers' => $showUsers,
            'friendListOne' => $friendListOne,
            'friendListTwo' => $friendListTwo,
        ]);
    }

    /**
     * @Route("/ajax/deleteGame", name="ajax_delete_game")
     */
    public function deleteGame(Request $request)
    {
        if ($request->isXmlHttpRequest() || $request->query->get('showJson') == 1) {  
            $return = false;
            $entityManager = $this->getDoctrine()->getManager();
            $games = $entityManager->getRepository(Games::class)->find($request->request->get('id'));
            
            if ($games) {
                $fileSystem = new Filesystem();
                $fileSystem->remove('images/games/'.$games->getNameImg());
                $entityManager->remove($games);
                $entityManager->flush();
                $return = true;
            }

            return new JsonResponse($return);
        } else {
            return $this->redirectToRoute('event');
        }
    }

}

templates/administration/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Administration{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('administration') }}
{% endblock %}

{% block body %}

<!-- Start modal add games -->
<div class="modal fade" id="modalAddGame" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Ajouter un jeu vidéo</h5>
                <button type="button" aria-label="Close modal" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {{ form_start(addGamesForm) }}
                <div class="row">
                    <div class="col-12">
                        {{ form_label(addGamesForm.name) }}
                        {{ form_widget(addGamesForm.name) }}
                    </div>
                    <div class="col-12 mt-2">
                        {{ form_label(addGamesForm.description) }}
                        {{ form_widget(addGamesForm.description) }}
                    </div>
                    <div class="col-12 mt-3">
                        {{ form_widget(addGamesForm.name_img) }}
                    </div>
                    <div class="col-12 mt-4">
                        <button type="button" aria-label="Close modal" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                        {{ form_widget(addGamesForm.save) }}
                    </div>
                </div>
                {{ form_end(addGamesForm) }}
            </div>
        </div>
    </div>
</div>
<!-- End modal add games -->

<div class="row">

    <div class="col-12"></div>

    <div class="col-lg-6 mb-4">
        <div class="cadreAdmin">
            <h3>Jeux Vidéos</h3>
            <button class="btn btn-warning btnAdd" aria-label="Add game"  data-bs-toggle="modal" data-bs-target="#modalAddGame">Ajouter</button>
            <div class="mt-4">
                <div class="table-responsive">
                    <table class="table" id="tableGames">
                        <thead>
                            <tr>
                            <th scope="col">Nom</th>
                            <th scope="col">Description</th>
                            <th scope="col">Image</th>
                            <th scope="col"></th>
                            </tr>
                        </thead>
                        <body>
                            {% for var in showGames %}
                            <tr>
                                <td>{{ var.name }}</td>
                                <td>{{ var.description }}</td>
                                <td>{{ var.nameImg }}</td>
                                <td><button class="btn btn-danger btnDeleteGame" aria-label="delete game" data-id="{{ var.id }}" data-name="{{ var.name }}"><i class="fas fa-trash"></i></button></td>
                            </tr>
                            {% endfor %}
                        </body>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-6 mb-4">
        <div class="cadreAdmin">
            <h3>Utilisateurs</h3>
            <div class="mt-4">
                <div class="table-responsive">
                    <table class="table" id="tableUsers">
                        <thead>
                            <tr>
                                <th scope="col">Pseudo</th>
                                <th scope="col">Email</th>
                                <th scope="col">Rôle</th>
                            </tr>
                        </thead>
                        <body>
                            {% for var in showUsers %}
                            <tr>
                                <td>{{ var.pseudo }}</td>
                                <td>{{ var.email }}</td>
                                <td>{{ var.roles[0] }}</td>
                            </tr>
                            {% endfor %}
                        </body>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
</div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('administration') }}
{% endblock %}